version: '3'

services:
  postgres:
    image: postgres

    restart: always
    volumes:
      - ./postgres:/data/db
    ports:
      - 5432:5433
    depends_on:
      - dask_way

  dask_way:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dask_way
    restart: unless-stopped
